import base64

import pytest
from fastapi.testclient import TestClient

from app.config import reset_settings_cache


def basic(user: str, password: str) -> dict[str, str]:
    return {"Authorization": "Basic " + base64.b64encode(f"{user}:{password}".encode()).decode()}


def test_site_password_protects_everything_but_health(db, monkeypatch):
    monkeypatch.setenv("USI_SITE_USERNAME", "boss")
    monkeypatch.setenv("USI_SITE_PASSWORD", "correct horse battery staple")
    reset_settings_cache()
    from app.main import create_app

    try:
        with TestClient(create_app()) as client:
            assert client.get("/api/health").status_code == 200
            denied = client.get("/api/projects")
            assert denied.status_code == 401 and denied.headers["www-authenticate"].startswith("Basic")
            assert client.get("/", headers=basic("boss", "wrong")).status_code == 401
            assert client.get("/api/projects", headers=basic("someone", "correct horse battery staple")).status_code == 401
            assert client.get("/api/projects", headers={"Authorization": "Basic !!notbase64"}).status_code == 401
            assert client.get("/api/projects", headers=basic("boss", "correct horse battery staple")).status_code == 200
    finally:
        monkeypatch.delenv("USI_SITE_PASSWORD")
        reset_settings_cache()


def test_master_key_accepts_fernet_key_or_long_passphrase(monkeypatch):
    from cryptography.fernet import Fernet

    from app.security.secrets import SecretConfigError, load_master_key

    try:
        fernet_key = Fernet.generate_key().decode()
        monkeypatch.setenv("USI_MASTER_KEY", fernet_key)
        reset_settings_cache()
        assert load_master_key() == fernet_key.encode()

        passphrase = "a long random value generated by the hosting platform 7f3a9c"
        monkeypatch.setenv("USI_MASTER_KEY", passphrase)
        reset_settings_cache()
        derived = load_master_key()
        Fernet(derived)  # valid key
        assert derived == load_master_key()  # deterministic across restarts

        monkeypatch.setenv("USI_MASTER_KEY", "too-short")
        reset_settings_cache()
        with pytest.raises(SecretConfigError):
            load_master_key()
    finally:
        monkeypatch.delenv("USI_MASTER_KEY", raising=False)
        reset_settings_cache()
