"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-13 16:12:14.919945
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_project_id'), ['project_id'], unique=False)

    op.create_table('encrypted_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=16), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_county'), ['county'], unique=False)

    op.create_table('provider_configs',
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_key')
    )
    op.create_table('rule_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('source_policies',
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('terms_acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('terms_acknowledged_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('workbook_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_sale_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('parser_key', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('detection', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('committed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_sale_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_sale_lists_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('locked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_property_id'), ['property_id'], unique=False)

    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_views_project_id'), ['project_id'], unique=False)

    op.create_table('export_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_records_project_id'), ['project_id'], unique=False)

    op.create_table('extracted_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imported_sale_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'row_index')
    )
    with op.batch_alter_table('extracted_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_rows_import_id'), ['import_id'], unique=False)

    op.create_table('refresh_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('changed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('user_action_needed', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_runs_project_id'), ['project_id'], unique=False)

    op.create_table('extracted_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('corrected', sa.Boolean(), nullable=False),
    sa.Column('corrected_by', sa.String(length=255), nullable=True),
    sa.Column('corrected_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['row_id'], ['extracted_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'field')
    )
    with op.batch_alter_table('extracted_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_values_row_id'), ['row_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('extracted_row_id', sa.Integer(), nullable=True),
    sa.Column('county', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('sale_number', sa.String(length=40), nullable=True),
    sa.Column('parcel_original', sa.String(length=64), nullable=False),
    sa.Column('parcel_normalized', sa.String(length=64), nullable=False),
    sa.Column('parcel_search_key', sa.String(length=64), nullable=True),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('mailing_address', sa.Text(), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('listed_amount', sa.Float(), nullable=True),
    sa.Column('listed_assessment', sa.Float(), nullable=True),
    sa.Column('listed_description', sa.String(length=255), nullable=True),
    sa.Column('listed_lot_size', sa.String(length=255), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_pilot', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('decision_status', sa.String(length=40), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('decision_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_enriched_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_row_id'], ['extracted_rows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['imported_sale_lists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'parcel_normalized')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_extracted_row_id'), ['extracted_row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_parcel_normalized'), ['parcel_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_project_id'), ['project_id'], unique=False)

    op.create_table('parcel_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'kind')
    )
    with op.batch_alter_table('parcel_identifiers', schema=None) as batch_op:
        batch_op.create_index('ix_parcel_identifier_kind_value', ['kind', 'value'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcel_identifiers_property_id'), ['property_id'], unique=False)

    op.create_table('property_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('stored_path', sa.Text(), nullable=True),
    sa.Column('provider_key', sa.String(length=60), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_images_property_id'), ['property_id'], unique=False)

    op.create_table('rule_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=True),
    sa.Column('rule_key', sa.String(length=60), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rule_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_rule_evaluation_current', ['property_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_evaluations_property_id'), ['property_id'], unique=False)

    op.create_table('sale_list_tax_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('cty_assessment', sa.Float(), nullable=True),
    sa.Column('sch_assessment', sa.Float(), nullable=True),
    sa.Column('twn_assessment', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_list_tax_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_list_tax_lines_property_id'), ['property_id'], unique=False)

    op.create_table('source_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('access_method', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('snapshot_bytes', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.String(length=30), nullable=False),
    sa.Column('captured_by', sa.String(length=255), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_evidence_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_evidence_source_key'), ['source_key'], unique=False)

    op.create_table('tax_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('checked_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('lookup_status', sa.String(length=40), nullable=False),
    sa.Column('status_text', sa.String(length=255), nullable=True),
    sa.Column('status_category', sa.String(length=20), nullable=True),
    sa.Column('balance_2024', sa.Float(), nullable=True),
    sa.Column('delinquent_total', sa.Float(), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('refresh_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refresh_run_id'], ['refresh_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_status_history_property_id'), ['property_id'], unique=False)

    op.create_table('user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('override_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('superseded_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_overrides_property_id'), ['property_id'], unique=False)

    op.create_table('assessment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.String(length=30), nullable=False),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('land_use_code', sa.String(length=20), nullable=True),
    sa.Column('land_use_description', sa.String(length=255), nullable=True),
    sa.Column('property_class', sa.String(length=60), nullable=True),
    sa.Column('property_type', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('school_district', sa.String(length=255), nullable=True),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('assessed_value', sa.Float(), nullable=True),
    sa.Column('assessed_land', sa.Float(), nullable=True),
    sa.Column('assessed_building', sa.Float(), nullable=True),
    sa.Column('lot_size_text', sa.String(length=120), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('lot_sqft', sa.Float(), nullable=True),
    sa.Column('building_style', sa.String(length=120), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('exterior_wall', sa.String(length=120), nullable=True),
    sa.Column('living_area_sqft', sa.Float(), nullable=True),
    sa.Column('base_area_sqft', sa.Float(), nullable=True),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('full_baths', sa.Integer(), nullable=True),
    sa.Column('half_baths', sa.Integer(), nullable=True),
    sa.Column('last_sale_date', sa.Date(), nullable=True),
    sa.Column('last_sale_price', sa.Float(), nullable=True),
    sa.Column('gross_building_area', sa.Float(), nullable=True),
    sa.Column('total_living_units', sa.Integer(), nullable=True),
    sa.Column('structure_description', sa.String(length=255), nullable=True),
    sa.Column('improvement_name', sa.String(length=255), nullable=True),
    sa.Column('commercial_living_area', sa.Float(), nullable=True),
    sa.Column('commercial_units', sa.Integer(), nullable=True),
    sa.Column('commercial_year_built', sa.Integer(), nullable=True),
    sa.Column('detail_link', sa.Text(), nullable=True),
    sa.Column('raw_codes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_records_property_id'), ['property_id'], unique=False)

    op.create_table('capture_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('search_hint', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_capture_task_open', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_tasks_property_id'), ['property_id'], unique=False)

    op.create_table('civil_lien_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.String(length=30), nullable=False),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('search_term', sa.Text(), nullable=True),
    sa.Column('case_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('classification', sa.String(length=255), nullable=True),
    sa.Column('case_type', sa.String(length=255), nullable=True),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'source_key', 'case_number')
    )
    with op.batch_alter_table('civil_lien_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_civil_lien_cases_property_id'), ['property_id'], unique=False)

    op.create_table('field_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_provenance', schema=None) as batch_op:
        batch_op.create_index('ix_field_provenance_current', ['property_id', 'field', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_provenance_property_id'), ['property_id'], unique=False)

    op.create_table('recorder_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.String(length=30), nullable=False),
    sa.Column('doc_key', sa.String(length=160), nullable=False),
    sa.Column('instrument_number', sa.String(length=80), nullable=True),
    sa.Column('book', sa.String(length=20), nullable=True),
    sa.Column('page', sa.String(length=20), nullable=True),
    sa.Column('doc_type_raw', sa.String(length=255), nullable=True),
    sa.Column('doc_category', sa.String(length=30), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.Column('grantors', sa.Text(), nullable=True),
    sa.Column('grantees', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('related_reference', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'source_key', 'doc_key')
    )
    with op.batch_alter_table('recorder_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recorder_documents_property_id'), ['property_id'], unique=False)

    op.create_table('source_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_lookups', schema=None) as batch_op:
        batch_op.create_index('ix_source_lookup_current', ['property_id', 'source_key', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_lookups_property_id'), ['property_id'], unique=False)

    op.create_table('tax_claim_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('entry_method', sa.String(length=30), nullable=False),
    sa.Column('retrieved_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('tax_sale_status', sa.String(length=255), nullable=True),
    sa.Column('status_category', sa.String(length=20), nullable=False),
    sa.Column('delinquent_total', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('assessed_value', sa.Float(), nullable=True),
    sa.Column('deed_book_page', sa.String(length=60), nullable=True),
    sa.Column('as_of_text', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_claim_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_claim_records_property_id'), ['property_id'], unique=False)

    op.create_table('valuation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('coverage_status', sa.String(length=40), nullable=False),
    sa.Column('provider_property_id', sa.String(length=120), nullable=True),
    sa.Column('estimate_type', sa.String(length=40), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('point', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimate_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('response_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.String(length=40), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('entry_method', sa.String(length=30), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_records_property_id'), ['property_id'], unique=False)

    op.create_table('assessment_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('grantor', sa.Text(), nullable=True),
    sa.Column('grantee', sa.Text(), nullable=True),
    sa.Column('book_page', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_sales_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('mortgage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=True),
    sa.Column('lender', sa.Text(), nullable=True),
    sa.Column('borrower', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('evaluated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_status', sa.String(length=60), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['recorder_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('mortgage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mortgage_records_property_id'), ['property_id'], unique=False)

    op.create_table('tax_claim_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_claim_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('face', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tax_claim_id'], ['tax_claim_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_claim_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_claim_years_tax_claim_id'), ['tax_claim_id'], unique=False)

    op.create_table('valuation_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('valuation_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('provider_key', sa.String(length=60), nullable=True),
    sa.Column('estimate_type', sa.String(length=40), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('computed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['valuation_id'], ['valuation_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_selections_property_id'), ['property_id'], unique=False)

    op.create_table('satisfaction_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('satisfaction_document_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgage_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['satisfaction_document_id'], ['recorder_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mortgage_id', 'satisfaction_document_id')
    )
    with op.batch_alter_table('satisfaction_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satisfaction_matches_mortgage_id'), ['mortgage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_satisfaction_matches_satisfaction_document_id'), ['satisfaction_document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satisfaction_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satisfaction_matches_satisfaction_document_id'))
        batch_op.drop_index(batch_op.f('ix_satisfaction_matches_mortgage_id'))

    op.drop_table('satisfaction_matches')
    with op.batch_alter_table('valuation_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_selections_property_id'))

    op.drop_table('valuation_selections')
    with op.batch_alter_table('tax_claim_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_claim_years_tax_claim_id'))

    op.drop_table('tax_claim_years')
    with op.batch_alter_table('mortgage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mortgage_records_property_id'))

    op.drop_table('mortgage_records')
    with op.batch_alter_table('assessment_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_sales_assessment_id'))

    op.drop_table('assessment_sales')
    with op.batch_alter_table('valuation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_records_property_id'))

    op.drop_table('valuation_records')
    with op.batch_alter_table('tax_claim_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_claim_records_property_id'))

    op.drop_table('tax_claim_records')
    with op.batch_alter_table('source_lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_lookups_property_id'))
        batch_op.drop_index('ix_source_lookup_current')

    op.drop_table('source_lookups')
    with op.batch_alter_table('recorder_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recorder_documents_property_id'))

    op.drop_table('recorder_documents')
    with op.batch_alter_table('field_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_provenance_property_id'))
        batch_op.drop_index('ix_field_provenance_current')

    op.drop_table('field_provenance')
    with op.batch_alter_table('civil_lien_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_civil_lien_cases_property_id'))

    op.drop_table('civil_lien_cases')
    with op.batch_alter_table('capture_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_tasks_property_id'))
        batch_op.drop_index(batch_op.f('ix_capture_tasks_project_id'))
        batch_op.drop_index('ix_capture_task_open')

    op.drop_table('capture_tasks')
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_records_property_id'))

    op.drop_table('assessment_records')
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_overrides_property_id'))

    op.drop_table('user_overrides')
    with op.batch_alter_table('tax_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_status_history_property_id'))

    op.drop_table('tax_status_history')
    with op.batch_alter_table('source_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_evidence_source_key'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_property_id'))
        batch_op.drop_index(batch_op.f('ix_source_evidence_project_id'))

    op.drop_table('source_evidence')
    with op.batch_alter_table('sale_list_tax_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_list_tax_lines_property_id'))

    op.drop_table('sale_list_tax_lines')
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_property_id'))
        batch_op.drop_index('ix_rule_evaluation_current')

    op.drop_table('rule_evaluations')
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_images_property_id'))

    op.drop_table('property_images')
    with op.batch_alter_table('parcel_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcel_identifiers_property_id'))
        batch_op.drop_index('ix_parcel_identifier_kind_value')

    op.drop_table('parcel_identifiers')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_project_id'))
        batch_op.drop_index(batch_op.f('ix_properties_parcel_normalized'))
        batch_op.drop_index(batch_op.f('ix_properties_import_id'))
        batch_op.drop_index(batch_op.f('ix_properties_extracted_row_id'))

    op.drop_table('properties')
    with op.batch_alter_table('extracted_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_values_row_id'))

    op.drop_table('extracted_values')
    with op.batch_alter_table('refresh_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_runs_job_id'))

    op.drop_table('refresh_runs')
    with op.batch_alter_table('extracted_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_rows_import_id'))

    op.drop_table('extracted_rows')
    with op.batch_alter_table('export_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_export_records_job_id'))

    op.drop_table('export_records')
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_views_project_id'))

    op.drop_table('saved_views')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_property_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_parent_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_idempotency_key'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('imported_sale_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_sale_lists_project_id'))

    op.drop_table('imported_sale_lists')
    op.drop_table('workbook_templates')
    op.drop_table('users')
    op.drop_table('source_policies')
    op.drop_table('rule_sets')
    op.drop_table('provider_configs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_county'))

    op.drop_table('projects')
    op.drop_table('encrypted_secrets')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
